In [1]:
import linreg
import multiple_gradient
import pandas
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
#from sklearn.linear_model import LinearRegression

In [2]:
df = pandas.read_csv('advertising.csv')
linreg = linreg.LinearRegression()
np.sum(df.isnull())

/home/miniloda/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [3]:
X = df[['TV', 'Radio']].values
y = df['Sales'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)
X_train

array([[ 36.9,  38.6],
       [ 31.5,  24.6],
       [142.9,  29.3],
       [209.6,  20.6],
       [215.4,  23.6],
       [102.7,  29.6],
       [  8.6,   2.1],
       [ 16.9,  43.7],
       [125.7,  36.9],
       [104.6,   5.7],
       [109.8,  14.3],
       [229.5,  32.3],
       [253.8,  21.3],
       [184.9,  21. ],
       [ 44.7,  25.8],
       [ 62.3,  12.6],
       [292.9,  28.3],
       [172.5,  18.1],
       [202.5,  22.3],
       [  7.3,  28.1],
       [265.2,   2.9],
       [197.6,   3.5],
       [218.5,   5.4],
       [147.3,  23.9],
       [171.3,  39.7],
       [217.7,  33.5],
       [262.7,  28.8],
       [163.5,  36.8],
       [100.4,   9.6],
       [ 76.3,  27.5],
       [184.9,  43.9],
       [134.3,   4.9],
       [273.7,  28.9],
       [296.4,  36.3],
       [ 96.2,  14.8],
       [109.8,  47.8],
       [255.4,  26.9],
       [204.1,  32.9],
       [240.1,  16.7],
       [193.7,  35.4],
       [191.1,  28.7],
       [ 89.7,   9.9],
       [ 43. ,  25.9],
       [ 38

In [4]:
linreg.fit(X_train, y_train)

(3, 160)
2
(160, 3)
2
[[1.60000000e+02 2.40829000e+04 3.74210000e+03]
 [2.40829000e+04 4.77253599e+06 5.72021790e+05]
 [3.74210000e+03 5.72021790e+05 1.22048630e+05]]


In [5]:
X[:,0]

array([230.1,  44.5,  17.2, 151.5, 180.8,   8.7,  57.5, 120.2,   8.6,
       199.8,  66.1, 214.7,  23.8,  97.5, 204.1, 195.4,  67.8, 281.4,
        69.2, 147.3, 218.4, 237.4,  13.2, 228.3,  62.3, 262.9, 142.9,
       240.1, 248.8,  70.6, 292.9, 112.9,  97.2, 265.6,  95.7, 290.7,
       266.9,  74.7,  43.1, 228. , 202.5, 177. , 293.6, 206.9,  25.1,
       175.1,  89.7, 239.9, 227.2,  66.9, 199.8, 100.4, 216.4, 182.6,
       262.7, 198.9,   7.3, 136.2, 210.8, 210.7,  53.5, 261.3, 239.3,
       102.7, 131.1,  69. ,  31.5, 139.3, 237.4, 216.8, 199.1, 109.8,
        26.8, 129.4, 213.4,  16.9,  27.5, 120.5,   5.4, 116. ,  76.4,
       239.8,  75.3,  68.4, 213.5, 193.2,  76.3, 110.7,  88.3, 109.8,
       134.3,  28.6, 217.7, 250.9, 107.4, 163.3, 197.6, 184.9, 289.7,
       135.2, 222.4, 296.4, 280.2, 187.9, 238.2, 137.9,  25. ,  90.4,
        13.1, 255.4, 225.8, 241.7, 175.7, 209.6,  78.2,  75.1, 139.2,
        76.4, 125.7,  19.4, 141.3,  18.8, 224. , 123.1, 229.5,  87.2,
         7.8,  80.2,

In [6]:
predictions = linreg.predict(X_test)

In [7]:
predictions

array([10.68000732,  8.67289687,  9.59627362, 24.89341048, 14.697364  ,
        8.3567853 , 10.55863443, 18.38868264,  9.85132079, 17.86927795,
       23.41528097, 10.68859833, 13.39700653, 17.10227442, 11.74725693,
       13.31442741, 21.15105215,  9.1078251 , 14.1508319 , 18.85894126,
       24.8577903 , 12.44648472, 16.57547935, 13.79888848,  7.80545687,
       15.11832283, 14.69260423, 20.6616562 , 16.98730791,  8.88795212,
       12.37433351, 20.80729034, 21.28995356, 21.8483045 ,  7.17317454,
        7.05033262,  9.23136496, 15.59516171, 13.27468497,  7.2670912 ])

In [8]:
y_test

array([11.3,  8.4, 12. , 25.4, 16.7,  8.7,  7.2, 18.2,  9.2, 16.6, 24.2,
       10.6, 15.5, 20.6, 11.8, 13.2, 17.4,  1.6, 14.7, 17. , 26.2, 10.3,
       16.1, 12.9,  8.1, 15.2, 17.6, 22.6, 16.6,  8.5, 12.5, 23.7, 16.1,
       21.8,  5.6,  6.7,  9.7, 17.9, 13.6,  7.2])

In [9]:
import multiple_gradient

In [10]:
linear_reg = multiple_gradient.LinearRegression()
linear_reg.fit(X_train, y_train)
predictions = linear_reg.predict(X_test)
print(predictions)

Did not converge after 100000 iterations . Try increasing max_iter.
[ 359.42661274  254.76464364  420.51144379 1415.51089776  802.00664574
  272.64276852  132.0416512  1123.34690952  176.6165409   956.44626775
 1285.30920774  426.62400138  729.87442128  907.27553067  403.8684078
  592.90985857 1263.94714202   78.2872965   437.21678728 1031.64482024
 1407.09968439  653.45941421  851.26707819  643.74903482  253.48237384
  633.49435255  784.79164508 1030.11383673 1040.23368625  165.5548742
  382.18336505 1009.79377522 1322.49247233 1186.4234307    92.91387739
  111.37503796  299.74753931  856.31695371  399.28274664  138.42302099]


In [11]:
X.shape

(200, 2)

In [12]:
J_arr = np.zeros(10000)
J_arr[1] = 2

In [13]:
def transpose(X):    # sourcery skip: use-itertools-product
    """
    Transposes a matrix

    Args:
        X ([array]): a nxm array
    """
    n = X.shape[0]
    m = X.shape[1]
    X_transpose = np.zeros(shape=(m,n))
    for m in range(X.shape[1]):
        for n in range(X.shape[0]):
            X_transpose[m][n] = X[n,m]
    return X_transpose

In [14]:
X_tranpose = transpose(X)
print(X_tranpose.shape)

(2, 200)
