In [8]:
from linreg import LinearRegression
import pandas
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
#from sklearn.linear_model import LinearRegression

In [9]:
df = pandas.read_csv('advertising.csv')
linreg = LinearRegression()
np.sum(df.isnull())

/home/miniloda/.local/lib/python3.10/site-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [10]:
X = df[['TV', 'Radio','Newspaper']].values
y = df['Sales'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)
X_train

array([[ 36.9,  38.6,  65.6],
       [ 31.5,  24.6,   2.2],
       [142.9,  29.3,  12.6],
       [209.6,  20.6,  10.7],
       [215.4,  23.6,  57.6],
       [102.7,  29.6,   8.4],
       [  8.6,   2.1,   1. ],
       [ 16.9,  43.7,  89.4],
       [125.7,  36.9,  79.2],
       [104.6,   5.7,  34.4],
       [109.8,  14.3,  31.7],
       [229.5,  32.3,  74.2],
       [253.8,  21.3,  30. ],
       [184.9,  21. ,  22. ],
       [ 44.7,  25.8,  20.6],
       [ 62.3,  12.6,  18.3],
       [292.9,  28.3,  43.2],
       [172.5,  18.1,  30.7],
       [202.5,  22.3,  31.6],
       [  7.3,  28.1,  41.4],
       [265.2,   2.9,  43. ],
       [197.6,   3.5,   5.9],
       [218.5,   5.4,  27.4],
       [147.3,  23.9,  19.1],
       [171.3,  39.7,  37.7],
       [217.7,  33.5,  59. ],
       [262.7,  28.8,  15.9],
       [163.5,  36.8,   7.4],
       [100.4,   9.6,   3.6],
       [ 76.3,  27.5,  16. ],
       [184.9,  43.9,   1.7],
       [134.3,   4.9,   9.3],
       [273.7,  28.9,  59.7],
       [29

In [11]:
linreg.fit(X_train, y_train)

In [12]:
predictions = linreg.predict(X_test)

In [13]:
predictions

array([10.70988945,  8.68629773,  9.5778695 , 24.86207988, 14.65584473,
        8.3214275 , 10.43048002, 18.4453765 ,  9.73394291, 17.9290798 ,
       23.369886  , 10.67916356, 13.44032325, 17.17416235, 11.77380187,
       13.37072678, 21.26009906,  9.19666875, 14.13201846, 18.9260716 ,
       24.75507991, 12.48481182, 16.57130583, 13.77344772,  7.79299106,
       15.19648316, 14.71607944, 20.73862119, 17.01041859,  8.83474391,
       12.09424377, 20.74886454, 21.26147987, 21.90420095,  7.08087067,
        7.04431681,  9.15949871, 15.47796148, 13.28282334,  7.23769883])

In [14]:
y_test

array([11.3,  8.4, 12. , 25.4, 16.7,  8.7,  7.2, 18.2,  9.2, 16.6, 24.2,
       10.6, 15.5, 20.6, 11.8, 13.2, 17.4,  1.6, 14.7, 17. , 26.2, 10.3,
       16.1, 12.9,  8.1, 15.2, 17.6, 22.6, 16.6,  8.5, 12.5, 23.7, 16.1,
       21.8,  5.6,  6.7,  9.7, 17.9, 13.6,  7.2])

In [7]:
r2 = r2_score(y_test, predictions)

In [8]:
r2

0.8645053923967727